dropout: 0.36
edge_embedding_operator: concat
embedding_size: 128
heads: null
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 0.00784823541381556
msg_passing: GCN
num_layers_mlp: 5
num_layers_msg: 4
num_x_features: 3
v2: null
