dropout: 0.36
edge_embedding_operator: mean
embedding_size: 32
heads: 4
loss_fn: MSE
loss_phi_fn: exponential
lr: 0.0016864924799815117
msg_passing: GAT
num_layers_mlp: 1
num_layers_msg: 2
num_x_features: 3
v2: false
