dropout: 0.24000000000000002
edge_embedding_operator: concat
embedding_size: 32
heads: 1
loss_fn: MSE
loss_phi_fn: exponential
lr: 0.006288153225839281
msg_passing: GAT
num_layers_mlp: 1
num_layers_msg: 2
num_x_features: 3
v2: true
