dropout: 0.26
edge_embedding_operator: concat
embedding_size: 256
heads: null
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 0.008135683332585431
msg_passing: GCN
num_layers_mlp: 3
num_layers_msg: 2
num_x_features: 3
v2: null
