dropout: 0.38
edge_embedding_operator: hadamard
embedding_size: 64
heads: null
loss_fn: RANK
loss_phi_fn: exponential
lr: 0.0007823766455329709
msg_passing: GCN
num_layers_mlp: 2
num_layers_msg: 4
num_x_features: 3
v2: null
