dropout: 0.24000000000000002
edge_embedding_operator: concat
embedding_size: 256
heads: null
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 0.0034612372663533515
msg_passing: GCN
num_layers_mlp: 1
num_layers_msg: 1
num_x_features: 3
v2: null
