dropout: 0.22
edge_embedding_operator: concat
embedding_size: 64
heads: null
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 0.003847442853416815
msg_passing: GCN
num_layers_mlp: 4
num_layers_msg: 1
num_x_features: 3
v2: null
