dropout: 0.22
edge_embedding_operator: concat
embedding_size: 32
heads: 2
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 0.005525283287329645
msg_passing: GAT
num_layers_mlp: 1
num_layers_msg: 2
num_x_features: 3
v2: true
