dropout: 0.32
edge_embedding_operator: mean
embedding_size: 128
heads: 4
loss_fn: MSE
loss_phi_fn: exponential
lr: 0.002349723826547178
msg_passing: GAT
num_layers_mlp: 2
num_layers_msg: 2
num_x_features: 3
v2: false
