dropout: 0.2
edge_embedding_operator: concat
embedding_size: 256
heads: 2
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 0.005733559307690211
msg_passing: GAT
num_layers_mlp: 3
num_layers_msg: 2
num_x_features: 3
v2: true
