dropout: 0.36
edge_embedding_operator: concat
embedding_size: 256
heads: 1
loss_fn: MSE
loss_phi_fn: exponential
lr: 0.005686294612959317
msg_passing: GAT
num_layers_mlp: 1
num_layers_msg: 3
num_x_features: 3
v2: true
