dropout: 0.38
edge_embedding_operator: hadamard
embedding_size: 64
heads: 8
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 0.009645853833788893
msg_passing: GAT
num_layers_mlp: 3
num_layers_msg: 3
num_x_features: 3
v2: false
