dropout: 0.2
edge_embedding_operator: concat
embedding_size: 256
heads: 1
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 0.002108568678882163
msg_passing: GAT
num_layers_mlp: 2
num_layers_msg: 2
num_x_features: 3
v2: false
