dropout: 0.32
edge_embedding_operator: mean
embedding_size: 64
heads: 8
loss_fn: RANK
loss_phi_fn: exponential
lr: 0.00019170041589170651
msg_passing: GAT
num_layers_mlp: 1
num_layers_msg: 4
num_x_features: 3
v2: false
