dropout: 0.28
edge_embedding_operator: mean
embedding_size: 32
heads: null
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 0.006228886287552834
msg_passing: GCN
num_layers_mlp: 1
num_layers_msg: 2
num_x_features: 3
v2: null
