dropout: 0.26
edge_embedding_operator: concat
embedding_size: 64
heads: 8
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 0.006871218202043777
msg_passing: GAT
num_layers_mlp: 1
num_layers_msg: 1
num_x_features: 3
v2: true
