dropout: 0.24000000000000002
edge_embedding_operator: mean
embedding_size: 32
heads: null
loss_fn: MSE
loss_phi_fn: exponential
lr: 1.3491843278385426e-05
msg_passing: GCN
num_layers_mlp: 1
num_layers_msg: 4
num_x_features: 3
v2: null
