dropout: 0.30000000000000004
edge_embedding_operator: concat
embedding_size: 32
heads: null
loss_fn: MSE
loss_phi_fn: exponential
lr: 0.0016660231165208695
msg_passing: GCN
num_layers_mlp: 2
num_layers_msg: 2
num_x_features: 3
v2: null
