dropout: 0.2
edge_embedding_operator: mean
embedding_size: 256
heads: null
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 0.005040307639554791
msg_passing: GCN
num_layers_mlp: 3
num_layers_msg: 2
num_x_features: 3
v2: null
