dropout: 0.28
edge_embedding_operator: concat
embedding_size: 128
heads: null
loss_fn: MSE
loss_phi_fn: exponential
lr: 0.0002084191577687999
msg_passing: GCN
num_layers_mlp: 3
num_layers_msg: 2
num_x_features: 3
v2: null
