dropout: 0.28
edge_embedding_operator: hadamard
embedding_size: 128
heads: null
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 0.007338689239723391
msg_passing: GCN
num_layers_mlp: 3
num_layers_msg: 4
num_x_features: 3
v2: null
