dropout: 0.2
edge_embedding_operator: mean
embedding_size: 32
heads: 2
loss_fn: MSE
loss_phi_fn: sqrt_exp
lr: 0.0009717775305059633
msg_passing: GAT
num_layers_mlp: 4
num_layers_msg: 3
num_x_features: 3
v2: true
