dropout: 0.26
edge_embedding_operator: concat
embedding_size: 128
heads: null
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 0.00617755414224655
msg_passing: GCN
num_layers_mlp: 1
num_layers_msg: 1
num_x_features: 3
v2: null
