dropout: 0.22
edge_embedding_operator: concat
embedding_size: 64
heads: null
loss_fn: RANK
loss_phi_fn: exponential
lr: 0.008065872740424083
msg_passing: GCN
num_layers_mlp: 1
num_layers_msg: 2
num_x_features: 3
v2: null
