dropout: 0.4
edge_embedding_operator: hadamard
embedding_size: 64
heads: null
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 0.005057908087000121
msg_passing: GCN
num_layers_mlp: 2
num_layers_msg: 1
num_x_features: 3
v2: null
