dropout: 0.36
edge_embedding_operator: concat
embedding_size: 256
heads: null
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 0.0037497213736314714
msg_passing: GCN
num_layers_mlp: 2
num_layers_msg: 2
num_x_features: 3
v2: null
