dropout: 0.24000000000000002
edge_embedding_operator: concat
embedding_size: 64
heads: 2
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 5.3156560571583175e-05
msg_passing: GAT
num_layers_mlp: 3
num_layers_msg: 1
num_x_features: 3
v2: false
