dropout: 0.24000000000000002
edge_embedding_operator: concat
embedding_size: 64
heads: 2
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 0.008392686163635548
msg_passing: GAT
num_layers_mlp: 2
num_layers_msg: 3
num_x_features: 3
v2: true
