dropout: 0.34
edge_embedding_operator: hadamard
embedding_size: 128
heads: null
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 0.004485508974438136
msg_passing: GCN
num_layers_mlp: 5
num_layers_msg: 1
num_x_features: 3
v2: null
