dropout: 0.22
edge_embedding_operator: concat
embedding_size: 256
heads: null
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 0.003274143749779673
msg_passing: GCN
num_layers_mlp: 2
num_layers_msg: 3
num_x_features: 3
v2: null
