dropout: 0.28
edge_embedding_operator: concat
embedding_size: 64
heads: 8
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 0.008156575567571043
msg_passing: GAT
num_layers_mlp: 3
num_layers_msg: 2
num_x_features: 3
v2: true
