dropout: 0.36
edge_embedding_operator: mean
embedding_size: 32
heads: null
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 0.007007140644630753
msg_passing: GCN
num_layers_mlp: 2
num_layers_msg: 1
num_x_features: 3
v2: null
