dropout: 0.4
edge_embedding_operator: concat
embedding_size: 256
heads: 2
loss_fn: MSE
loss_phi_fn: exponential
lr: 0.00033729175193198324
msg_passing: GAT
num_layers_mlp: 4
num_layers_msg: 5
num_x_features: 3
v2: true
