dropout: 0.28
edge_embedding_operator: concat
embedding_size: 64
heads: 2
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 0.008347317501077622
msg_passing: GAT
num_layers_mlp: 3
num_layers_msg: 1
num_x_features: 3
v2: true
