dropout: 0.36
edge_embedding_operator: concat
embedding_size: 256
heads: 8
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 2.1387290754148914e-05
msg_passing: GAT
num_layers_mlp: 3
num_layers_msg: 2
num_x_features: 3
v2: true
