dropout: 0.2
edge_embedding_operator: concat
embedding_size: 64
heads: 2
loss_fn: RANK
loss_phi_fn: exponential
lr: 0.004657874725661101
msg_passing: GAT
num_layers_mlp: 1
num_layers_msg: 2
num_x_features: 3
v2: true
