dropout: 0.32
edge_embedding_operator: concat
embedding_size: 256
heads: null
loss_fn: MSE
loss_phi_fn: exponential
lr: 0.0028872407332002172
msg_passing: GCN
num_layers_mlp: 1
num_layers_msg: 2
num_x_features: 3
v2: null
