dropout: 0.32
edge_embedding_operator: mean
embedding_size: 256
heads: 1
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 0.005650870009893549
msg_passing: GAT
num_layers_mlp: 1
num_layers_msg: 3
num_x_features: 3
v2: false
