dropout: 0.32
edge_embedding_operator: concat
embedding_size: 128
heads: null
loss_fn: MSE
loss_phi_fn: exponential
lr: 0.00011769515602040156
msg_passing: GCN
num_layers_mlp: 4
num_layers_msg: 1
num_x_features: 3
v2: null
