dropout: 0.32
edge_embedding_operator: concat
embedding_size: 128
heads: 8
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 0.0002680721861751299
msg_passing: GAT
num_layers_mlp: 1
num_layers_msg: 2
num_x_features: 3
v2: true
