dropout: 0.26
edge_embedding_operator: concat
embedding_size: 256
heads: null
loss_fn: MSE
loss_phi_fn: exponential
lr: 7.991621920384351e-05
msg_passing: GCN
num_layers_mlp: 3
num_layers_msg: 1
num_x_features: 3
v2: null
