dropout: 0.34
edge_embedding_operator: concat
embedding_size: 256
heads: null
loss_fn: MSE
loss_phi_fn: exponential
lr: 0.0013273236118803604
msg_passing: GCN
num_layers_mlp: 1
num_layers_msg: 3
num_x_features: 3
v2: null
