dropout: 0.34
edge_embedding_operator: concat
embedding_size: 32
heads: null
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 0.005693477513481756
msg_passing: GCN
num_layers_mlp: 5
num_layers_msg: 2
num_x_features: 3
v2: null
