dropout: 0.2
edge_embedding_operator: concat
embedding_size: 64
heads: 8
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 0.004136810146927331
msg_passing: GAT
num_layers_mlp: 4
num_layers_msg: 3
num_x_features: 3
v2: true
