dropout: 0.22
edge_embedding_operator: concat
embedding_size: 32
heads: null
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 0.00010347593489217386
msg_passing: GCN
num_layers_mlp: 3
num_layers_msg: 2
num_x_features: 3
v2: null
