dropout: 0.2
edge_embedding_operator: hadamard
embedding_size: 256
heads: null
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 0.0052217915894049415
msg_passing: GCN
num_layers_mlp: 4
num_layers_msg: 2
num_x_features: 3
v2: null
