dropout: 0.30000000000000004
edge_embedding_operator: hadamard
embedding_size: 256
heads: null
loss_fn: MSE
loss_phi_fn: exponential
lr: 1.0045018315729202e-05
msg_passing: GCN
num_layers_mlp: 2
num_layers_msg: 4
num_x_features: 3
v2: null
