dropout: 0.36
edge_embedding_operator: concat
embedding_size: 256
heads: 2
loss_fn: MSE
loss_phi_fn: exponential
lr: 0.0010066632822275739
msg_passing: GAT
num_layers_mlp: 4
num_layers_msg: 4
num_x_features: 3
v2: true
