dropout: 0.36
edge_embedding_operator: concat
embedding_size: 64
heads: null
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 0.007769081478545467
msg_passing: GCN
num_layers_mlp: 2
num_layers_msg: 2
num_x_features: 3
v2: null
