dropout: 0.22
edge_embedding_operator: hadamard
embedding_size: 64
heads: 8
loss_fn: RANK
loss_phi_fn: exponential
lr: 0.004995758569512508
msg_passing: GAT
num_layers_mlp: 1
num_layers_msg: 3
num_x_features: 3
v2: false
