dropout: 0.22
edge_embedding_operator: hadamard
embedding_size: 256
heads: null
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 7.772536040549746e-05
msg_passing: GCN
num_layers_mlp: 5
num_layers_msg: 1
num_x_features: 3
v2: null
