dropout: 0.2
edge_embedding_operator: concat
embedding_size: 256
heads: null
loss_fn: MSE
loss_phi_fn: sqrt_exp
lr: 0.0049187271503895675
msg_passing: GCN
num_layers_mlp: 3
num_layers_msg: 2
num_x_features: 3
v2: null
