dropout: 0.26
edge_embedding_operator: concat
embedding_size: 64
heads: 2
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 0.009992054371909326
msg_passing: GAT
num_layers_mlp: 1
num_layers_msg: 2
num_x_features: 3
v2: true
