dropout: 0.32
edge_embedding_operator: mean
embedding_size: 256
heads: null
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 0.00325013123792113
msg_passing: GCN
num_layers_mlp: 5
num_layers_msg: 2
num_x_features: 3
v2: null
