dropout: 0.24000000000000002
edge_embedding_operator: concat
embedding_size: 32
heads: null
loss_fn: MSE
loss_phi_fn: exponential
lr: 0.0024404240425670762
msg_passing: GCN
num_layers_mlp: 2
num_layers_msg: 2
num_x_features: 3
v2: null
