dropout: 0.2
edge_embedding_operator: concat
embedding_size: 256
heads: 4
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 0.0020901721525741104
msg_passing: GAT
num_layers_mlp: 4
num_layers_msg: 2
num_x_features: 3
v2: false
