dropout: 0.38
edge_embedding_operator: mean
embedding_size: 128
heads: 1
loss_fn: MSE
loss_phi_fn: exponential
lr: 0.0018709724200887195
msg_passing: GAT
num_layers_mlp: 3
num_layers_msg: 1
num_x_features: 3
v2: false
