dropout: 0.34
edge_embedding_operator: hadamard
embedding_size: 256
heads: 4
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 0.0007627573850932726
msg_passing: GAT
num_layers_mlp: 1
num_layers_msg: 3
num_x_features: 3
v2: true
