dropout: 0.2
edge_embedding_operator: mean
embedding_size: 32
heads: null
loss_fn: MSE
loss_phi_fn: exponential
lr: 0.0024734184878505805
msg_passing: GCN
num_layers_mlp: 2
num_layers_msg: 1
num_x_features: 3
v2: null
