dropout: 0.24000000000000002
edge_embedding_operator: concat
embedding_size: 256
heads: null
loss_fn: RANK
loss_phi_fn: sqrt_exp
lr: 0.00637866344060661
msg_passing: GCN
num_layers_mlp: 5
num_layers_msg: 1
num_x_features: 3
v2: null
